First homework
anderlex/iosSchool_HH pull request #1
Opened 2023-10-25 11:50 UTC by anderlex

2023-10-28 06:38 UTC, vaganova-ann requested changes

2023-10-28 06:38 UTC, vaganova-ann commented on iosSchool_HH/CharacterGenerator.swift
> +struct Location {
Давай во всех структурах и классах сменим переменные (var) на константы (let)

2023-10-28 06:38 UTC, vaganova-ann commented on iosSchool_HH/CharacterGenerator.swift
> +    enum Gender: String, CaseIterable {
енамы Gender и Status перенесем в начало класса Character, перед его свойствами

2023-10-28 06:38 UTC, vaganova-ann commented on iosSchool_HH/CharacterGenerator.swift
> +        static func randomGender() -> Gender {
отдели функцию от кейсов пустой строкой

2023-10-28 06:38 UTC, vaganova-ann commented on iosSchool_HH/CharacterGenerator.swift
> +        static func randomStatus() -> Status {
отдели функцию от кейсов пустой строкой

2023-10-28 06:38 UTC, vaganova-ann commented on iosSchool_HH/CharacterGenerator.swift
> +    let names: [String] = ["Alex", "Jon", "Mark"]
свойства этого класса должны быть доступны или должны быть приватными?

2023-10-28 06:38 UTC, vaganova-ann commented on iosSchool_HH/CharacterGenerator.swift
> +    func generator() -> Character {
отдели пустой строкой свойства от функции

2023-10-28 06:38 UTC, vaganova-ann commented on iosSchool_HH/CharacterGenerator.swift
> +        return Character(id: Int.random(in: 1..<100000),
Открывающая и закрывающая скобки должны быть на отдельный строчках
init(
id: Int.random(in: 1..<100000),
name: names.randomElement() ?? "Unnamed",
species: specieses.randomElement() ?? "Who are you?",
итд
) {

2023-10-28 07:08 UTC, vaganova-ann requested changes

2023-10-28 07:08 UTC, vaganova-ann commented on iosSchool_HH/CharacterGenerator.swift
> +    init(id: Int, name: String, species: String, image: String, url: String,
Открывающая и закрывающая скобки должны быть на отдельный строчках и каждое свойство должно быть на отдельной строке
init(
id: Int, 
name: String, 
species: String
итд
) {

2023-10-29 13:46 UTC, anderlex commented on iosSchool_HH/CharacterGenerator.swift
> +    let names: [String] = ["Alex", "Jon", "Mark"]
пусть они будут доступные

2023-10-29 16:21 UTC, vaganova-ann commented on iosSchool_HH/CharacterGenerator.swift
> +    let names: [String] = ["Alex", "Jon", "Mark"]
тогда нарушается инкапсуляция

2023-10-29 16:21 UTC, vaganova-ann requested changes
Три замечания не поправлено

2023-10-30 04:16 UTC, vaganova-ann approved these changes

2023-10-30 10:37 UTC, merged