hw-14 cell data done
anderlex/iosSchool_HH pull request #18
Opened 2023-12-14 11:37 UTC by anderlex

2023-12-15 14:34 UTC, vaganova-ann requested changes
1) Не отображается плейсхолдер изображения и индикация загрузки на ячейках CharactersCell
2) Отступы на CharactersView не по дизайну
3) Ячейка CharactersCell не по дизайну
4) для стек вью в CharactersCell не нужен CenterX констрейнт

2023-12-15 14:34 UTC, vaganova-ann commented on iosSchool_HH/Modules/Characters/CharactersViewController.swift
> +        rootView.backgroundColor = UIColor(red: 0.769, green: 0.769, blue: 0.769, alpha: 1)
договорились цвета вынести в ассеты и использовать через ассеты

2023-12-15 14:34 UTC, vaganova-ann commented on iosSchool_HH/Modules/Characters/CharactersViewController.swift
> +                            isLoading: true,
почему true?

2023-12-15 14:34 UTC, vaganova-ann commented on iosSchool_HH/Modules/Characters/Subviews/CharactersCell.swift
> +    @IBOutlet private weak var stackView: UIStackView!
зачем тебе stackView здесь?

2023-12-15 20:43 UTC, anderlex commented on iosSchool_HH/Modules/Characters/Subviews/CharactersCell.swift
> +    @IBOutlet private weak var stackView: UIStackView!
я только увидел сообщения, подправлю завтра)

2023-12-17 09:52 UTC, vaganova-ann requested changes
1) В верстке CharactersCell проиходит что-то непонятное. Слишком много констрейнтов для изображения и нет bottom констрейнта. Индикация должна быть посередине ячейки, а не изображения.

2023-12-17 09:52 UTC, vaganova-ann commented on iosSchool_HH/Modules/Characters/CharactersView.swift
> +        customCell.layer.cornerRadius = 15
все настройки ячейки должны быть в ячейке. так же обрати внимание на то, что настройки, которые можно осуществить один раз, должны находиться в функции awakeFromNib

2023-12-17 09:52 UTC, vaganova-ann commented on iosSchool_HH/Modules/Characters/CharactersViewController.swift
> +                        guard let image else {
а если изображение не загрузилось, то у тебя с этим гардом всегда будет отображаться индикатор загрузки. нужно, чтобы индикация загрузки скрывалась, когда у нас больше ничего не грузится, а если изображение не пришло, то остается плейсхолдер

2023-12-17 09:52 UTC, vaganova-ann commented on iosSchool_HH/Modules/Characters/CharactersViewController.swift
> +                            ))
отступ у скобки неправильный

2023-12-17 09:52 UTC, vaganova-ann commented on iosSchool_HH/Modules/Characters/Subviews/CharactersCell.swift
> +        section.contentInsets = NSDirectionalEdgeInsets(top: 59, leading: 16, bottom: 59, trailing: 16)
bottom отступ не 59

2023-12-18 14:24 UTC, vaganova-ann requested changes

2023-12-18 14:24 UTC, vaganova-ann commented on iosSchool_HH/Modules/Characters/CharactersViewController.swift
> +                        guard let image else {
нет, такой вариант тоже не очень, получается дублирование кода, проще убрать гард совсем, а уже в update ячейки сделать что-то типа 
imageview.image = image ?? UIImage(named: "placeholder-image")

2023-12-19 14:51 UTC, vaganova-ann approved these changes

2023-12-19 17:07 UTC, merged